export var datas = [{
    id: 1,
    game_id: 1 - 1,
    category: "soccer",
    gameHead: "哈薩克斯坦甲組聯賽",
    time: ["1-1", "上半場", "45:24", "N"],
    team: ["奧杜斯基克", "阿特勞", "和局"],
    modal: "9",
    single: ["4.20", "2.35", "2.20"],
    spreadScore: ["", "0/0.5", ""],
    spread: ["1.87", "1.97", ""],
    overUnderScore: ["3", "", ""],
    overUnder: ["1.82", "2.00", ""],
    secondHalfSingle: ["<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>"],
    secondHalfSpreadScore: ["", "", ""],
    secondHalfSpread: ["<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>", ""],
    secondHalfOverUnderScore: ["2.5", "", ""],
    secondHalfOverUnder: ["<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>", ""],
    myFavorite: false,

}, {
    id: 2,
    game_id: 1 - 1,
    category: "soccer",
    gameHead: "哈薩克斯坦甲組聯賽",
    time: ["1-1", "上半場", "45:24", "N"],
    team: ["奧杜斯基克", "阿特勞", "和局"],
    downSingle: ["", ""],
    downSpreadScore: ["", "0.5"],
    downSpread: ["1.57", "2.36"],
    downOverUnderScore: ["3/3.5", ""],
    downOverUnder: ["2.26", "1.61"],
    downSecondHalfSingle: ["", ""],
    downSecondHalfSpreadScore: ["", "0/0.5"],
    downSecondHalfSpread: ["<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>"],
    downSecondHalfOverUnderScore: ["", ""],
    downSecondHalfOverUnder: ["", ""],
    myFavorite: true,
}, {
    id: 3,
    game_id: 2 - 1,
    category: "soccer",
    gameHead: "電競足球-FIFA20 CLA德國盃-10分鐘比賽",
    time: ["2-1", "上半場", "03:41", ""],
    team: ["Bayern Munich (Praym) Esports", "Rb Leipzig (Dimqaa) Esports", "和局"],
    modal: "11",
    single: ["4.35", "1.62", "3.30"],
    spreadScore: ["0/0.5", "", ""],
    spread: ["1.84", "1.86", ""],
    overUnderScore: ["2.5/3", "", ""],
    overUnder: ["1.81", "1.89", ""],
    secondHalfSingle: ["15.0", "1.16", "4.45"],
    secondHalfSpreadScore: ["0", "", ""],
    secondHalfSpread: ["1.56", "2.16", ""],
    secondHalfOverUnderScore: ["1.5", "", ""],
    secondHalfOverUnder: ["2.14", "1.57", ""],
    myFavorite: false
}, {
    id: 4,
    game_id: 2 - 1,
    category: "soccer",
    gameHead: "電競足球-FIFA20 CLA德國盃-10分鐘比賽",
    time: ["2-1", "上半場", "03:41", ""],
    team: ["Bayern Munich (Praym) Esports", "Rb Leipzig (Dimqaa) Esports", "和局"],
    downSingle: ["", ""],
    downSpreadScore: ["0.5", ""],
    downSpread: ["2.07", "1.63"],
    downOverUnderScore: ["2.5/3", ""],
    downOverUnder: ["1.71", "1.99"],
    downSecondHalfSingle: ["", ""],
    downSecondHalfSpreadScore: ["0/0.5", ""],
    downSecondHalfSpread: ["2.58", "1.33"],
    downSecondHalfOverUnderScore: ["1.5/2", ""],
    downSecondHalfOverUnder: ["2.72", "1.28"],
    myFavorite: false,
}, {
    id: 5,
    game_id: 3 - 1,
    category: "soccer",
    gameHead: "電競足球-決戰-8分鐘比賽",
    time: ["0-1", "上半場", "03:55", ""],
    team: ["Sevilla(Blulevard Prospect)", "Barcelona(DangerDim77) Esports", "和局"],
    modal: "3",
    single: ["10.5", "1.25", "3.90"],
    spreadScore: ["0", "", ""],
    spread: ["1.79", "1.91", ""],
    overUnderScore: ["1.52/2", "", ""],
    overUnder: ["1.78", "1.92", ""],
    secondHalfSingle: ["<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>"],
    secondHalfSpreadScore: ["", "", ""],
    secondHalfSpread: ["<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>", ""],
    secondHalfOverUnderScore: ["1.5", "", ""],
    secondHalfOverUnder: ["<img src='images/pngwing.com.png'>", "<img src='images/pngwing.com.png'>", ""],
    myFavorite: false
}, {
    id: 6,
    game_id: 3 - 1,
    category: "soccer",
    gameHead: "電競足球-決戰-8分鐘比賽",
    time: ["0-1", "上半場", "03:55", ""],
    team: ["Sevilla(Blulevard Prospect)", "Barcelona(DangerDim77) Esports", "和局"],
    downSingle: ["", ""],
    downSpreadScore: ["0/0.5", ""],
    downSpread: ["2.38", "1.42"],
    downOverUnderScore: ["1.5", ""],
    downOverUnder: ["1.54", "2.19"],
    downSecondHalfSingle: ["", ""],
    downSecondHalfSpreadScore: ["", ""],
    downSecondHalfSpread: ["", ""],
    downSecondHalfOverUnderScore: ["", ""],
    downSecondHalfOverUnder: ["", ""],
    myFavorite: false,
}, {
    id: 7,
    game_id: 4 - 1,
    category: "basketball",
    gameHead: "NBA2K-CYBER NBA ALL STARS LEAGUE(4X5MINS)",
    time: ["18-21", "第二節", "02:06"],
    team: ["休斯敦火箭 (SLAMDUNKVV)", "丹佛掘金 (HURRICANE)"],
    modal: "7",
    single: ["", ""],
    spreadScore: ["", ""],
    spread: ["", ""],
    overUnderScore: [
        ["大", "115.5"],
        ["小", "115.5"]
    ],
    myFavorite: false,
    overUnder: ["", ""],
    TeamOverUnderScore: ["", ""],
    TeamOverUnder: ["", ""]
}, {
    id: 8,
    game_id: 4 - 1,
    category: "basketball",
    gameHead: "NBA2K-CYBER NBA ALL STARS LEAGUE(4X5MINS)",
    time: ["17-21", "第二節", "03:30"],
    twoteam: ["雅特蘭大老鷹 (MVP)", "金州勇士 (Shiva)"],
    twomodal: "12",
    twosingle: ["", ""],
    twospreadScore: ["", "5.5"],
    twospread: ["1.85", "1.86"],
    twooverUnderScore: [
        ["大", "115.5"],
        ["小", "115.5"]
    ],
    twooverUnder: ["1.80", "1.81"],
    twoTeamOverUnderScore: ["", ""],
    twoTeamOverUnder: ["", ""],
    myFavorite: false,
}]